<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Pardeeps-MacBook-Pro.local" failures="1" tests="8" name="Personal Loan" time="0.1" errors="0" timestamp="2024-09-27T21:38:23 IST">
  <testcase classname="test.Day2" name="lastTest1" time="0.008"/>
  <testcase classname="test.Day1" name="Demo" time="0.01"/>
  <testcase classname="test.Day2" name="newTest" time="0.004"/>
  <testcase classname="test.Day1" name="SecondTest" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Day1.SecondTest(Day1.java:30)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- SecondTest -->
  <testcase classname="test.Day2" name="newTest1" time="0.01"/>
  <testcase classname="test.Day2" name="myTest1" time="0.001"/>
  <testcase classname="test.Day2" name="myTest1" time="0.005"/>
  <testcase classname="test.Day2" name="myTest1" time="0.002"/>
</testsuite> <!-- Personal Loan -->
